image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - mkaufman.HTMLHint
    - eventyret.bootstrap-4-cdn-snippet
    - kevinglasson.cornflakes-linter
    - hookyqr.beautify
    - samuelcolvin.jinjahtml@0.16.0:0559a632af4074fc5b1a8a281e78e352
    - wholroyd.jinja@0.0.8:0b7cec8f59d9c5225987f11c57a1e396
    - janne252.fontawesome-autocomplete@1.1.2:ec784a4e3f21c686c46add57014b0db6